//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas_Drivers
    {
        public int S_No { get; set; }
        public short Branch_No { get; set; }
        public int Dr_No { get; set; }
        public bool S_Priority { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
