//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_Backup
    {
        public int Id { get; set; }
        public Nullable<short> UserID { get; set; }
        public Nullable<int> Back_Type { get; set; }
        public string Back_Name { get; set; }
        public string Back_Path { get; set; }
        public Nullable<System.DateTime> Back_Start { get; set; }
        public Nullable<int> Week_Day { get; set; }
        public Nullable<System.DateTime> Back_Time { get; set; }
        public Nullable<System.DateTime> Back_Date { get; set; }
        public string Back_JobId { get; set; }
    
        public virtual User User { get; set; }
    }
}
