//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCode_Setup
    {
        public short Branch_No { get; set; }
        public string Weight_Begin { get; set; }
        public Nullable<short> Barcode_No_Length { get; set; }
        public Nullable<short> Item_No_Length { get; set; }
        public Nullable<int> Weight_Basic { get; set; }
        public bool Weight_Begin_Align { get; set; }
        [JsonIgnore]
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
