//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_details = new HashSet<Bill_details>();
        }
    
        public double Bill_No { get; set; }
        public short Bill_Pay_Type { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<double> Bill_Amt { get; set; }
        public Nullable<double> Disc_Amt { get; set; }
        public Nullable<double> Tax_Value { get; set; }
        public int Disc_Per { get; set; }
        public int Tax_Per { get; set; }
        public string Cost_Center { get; set; }
        public bool Posted { get; set; }
        public Nullable<short> F_Year { get; set; }
        public Nullable<short> F_Branch { get; set; }
        public int Restaurant_No { get; set; }
        public Nullable<short> W_Code { get; set; }
        public Nullable<short> Out_W_Code { get; set; }
        public Nullable<double> Extra_Amt { get; set; }
        public int Order_No { get; set; }
        public short CR_Card_No { get; set; }
        public long Cust_No { get; set; }
        public int Emp_No { get; set; }
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public string A_Code { get; set; }
        public int Cash_No { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<short> U_ID { get; set; }
        public bool RT_Bill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_details> Bill_details { get; set; }
    }
}
