//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_details
    {
        public Nullable<double> Bill_No { get; set; }
        public Nullable<short> Bill_Pay_Type { get; set; }
        public Nullable<short> F_Year { get; set; }
        public Nullable<short> F_Branch { get; set; }
        public Nullable<int> Restaurant_No { get; set; }
        public Nullable<short> W_Code { get; set; }
        public Nullable<short> Out_W_Code { get; set; }
        public string I_Code { get; set; }
        public Nullable<double> I_Qty { get; set; }
        public Nullable<double> Tmp_Qty { get; set; }
        public Nullable<double> I_Price { get; set; }
        public Nullable<double> Disc_Amt { get; set; }
        public Nullable<double> Tax_Value { get; set; }
        public Nullable<double> Extra_Amt { get; set; }
        public int Disc_Per { get; set; }
        public int Tax_Per { get; set; }
        public Nullable<System.DateTime> P_Date { get; set; }
        public bool Posted { get; set; }
        public Nullable<double> Doc_No { get; set; }
        public string BarCode_No { get; set; }
        public int Order_No { get; set; }
        public string ITM_UNT { get; set; }
        public Nullable<float> P_SIZE { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<double> S_ID { get; set; }
        public bool RT_Bill { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
