//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills_Components
    {
        public long ASerial { get; set; }
        public int Food_Parent_No { get; set; }
        public int Food_No { get; set; }
        public Nullable<double> Food_Qty { get; set; }
        public short Branch_No { get; set; }
        public bool Mandatory { get; set; }
        public int POS_No { get; set; }
        public double S_ID { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
