//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanceledOrder_D
    {
        public long CID { get; set; }
        public long ASerial { get; set; }
        public string Food_Name { get; set; }
        public int Food_No { get; set; }
        public Nullable<double> Food_Price { get; set; }
        public Nullable<double> FoodPriceVAT { get; set; }
        public Nullable<short> Food_Type { get; set; }
        public Nullable<int> Order_No { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> S_Qty { get; set; }
        public double S_Size { get; set; }
        public short Branch_No { get; set; }
        public Nullable<long> Serial_Code { get; set; }
        public string Food_Note { get; set; }
        public string Unit_Code { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
        public int POS_No { get; set; }
        public Nullable<double> Ins_Amount { get; set; }
        public Nullable<short> W_Code { get; set; }
        public int G_No { get; set; }
        public Nullable<double> S_ID { get; set; }
        public int ID { get; set; }
    
        public virtual CanceledOrder_H CanceledOrder_H { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
