//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmConsume_DTL
    {
        public Nullable<int> Doc_No { get; set; }
        public int Food_No { get; set; }
        public Nullable<double> I_QTY { get; set; }
        public Nullable<short> W_CODE { get; set; }
        public string Food_Desc { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<int> RCRD_No { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
