//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons_Dtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupons_Dtl()
        {
            this.HstrRest_H = new HashSet<HstrRest_H>();
            this.Restaurant_H = new HashSet<Restaurant_H>();
        }
    
        public Nullable<int> Trans_ID { get; set; }
        public string Coupon_No { get; set; }
        public Nullable<double> Coupon_Amount { get; set; }
        public Nullable<double> Rem_Coupon_Amount { get; set; }
        public bool Processed { get; set; }
        public string Coupon_Desc { get; set; }
        public bool InActive { get; set; }
        public Nullable<System.DateTime> Coupon_Expire_Date { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Coupons_Mst Coupons_Mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HstrRest_H> HstrRest_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_H> Restaurant_H { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
