//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Accounts
    {
        public long Customer_No { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Customer_Type { get; set; }
        public string Account_No { get; set; }
        public string C_Code { get; set; }
        public short CV_Type { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
