//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Types
    {
        public int Type_No { get; set; }
        public string Type_Name_L { get; set; }
        public string Type_Name_F { get; set; }
        public int Card_Disc { get; set; }
        public Nullable<double> Type_Disc { get; set; }
        public short Branch_No { get; set; }
        public short Act_No { get; set; }
    }
}
