//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Payment
    {
        public int Trans_ID { get; set; }
        public bool Trans_Type { get; set; }
        public Nullable<System.DateTime> Trans_Date { get; set; }
        public Nullable<System.DateTime> Trans_Time { get; set; }
        public Nullable<long> Customer_No { get; set; }
        public Nullable<short> User_ID { get; set; }
        public decimal Pay_Amount { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public string T_Desc { get; set; }
        public bool Posted { get; set; }
        public bool Acc_Posted { get; set; }
        public short Branch_No { get; set; }
        public bool BalancePastYear { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual User User { get; set; }
    }
}
