//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Promo_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Promo_MST()
        {
            this.Customer_Promo_DTL = new HashSet<Customer_Promo_DTL>();
        }
    
        public int Promo_No { get; set; }
        public Nullable<System.DateTime> Promo_Date { get; set; }
        public Nullable<short> Promo_Type { get; set; }
        public string Promo_Desc { get; set; }
        public string Promo_MSGTXT { get; set; }
        public Nullable<System.DateTime> Promo_FDate { get; set; }
        public Nullable<System.DateTime> Promo_TDate { get; set; }
        public Nullable<double> Promo_Amt { get; set; }
        public bool SendSms { get; set; }
        public bool B_Sync { get; set; }
        public Nullable<short> User_ID { get; set; }
        public short Branch_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Promo_DTL> Customer_Promo_DTL { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
