//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Promo_DTL
    {
        public int Promo_No { get; set; }
        public long Customer_No { get; set; }
        public Nullable<System.DateTime> Promo_Date { get; set; }
        public bool Promo_Actv { get; set; }
        public Nullable<short> Promo_Type { get; set; }
        public Nullable<double> Promo_Amt { get; set; }
        public string Tel_No { get; set; }
        public Nullable<int> RCRD_No { get; set; }
        public bool SendMSG { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Customer_Promo_MST Customer_Promo_MST { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
