//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteRest
    {
        public long ASerial { get; set; }
        public int Food_No { get; set; }
        public Nullable<double> Food_Price { get; set; }
        public Nullable<int> Order_No { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> S_Qty { get; set; }
        public double S_Size { get; set; }
        public Nullable<int> Service_No { get; set; }
        public short Branch_No { get; set; }
        public Nullable<long> Serial_Code { get; set; }
        public Nullable<int> Order_Serial { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<int> Order_Restart { get; set; }
        public string Unit_Code { get; set; }
        public string BarCode_No { get; set; }
        public Nullable<short> Bill_Serial_Type { get; set; }
        public Nullable<int> Bill_Serial_No { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
        public int POS_No { get; set; }
        public bool Food_Free { get; set; }
        public Nullable<double> Real_Price { get; set; }
        public Nullable<double> Serial_No { get; set; }
        public int Sub_Item { get; set; }
        public double S_ID { get; set; }
        public bool RptPrinted { get; set; }
        public int Sync_No { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public string CancelDesc { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual POS POS { get; set; }
        public virtual User User { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
