//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_DTL
    {
        public int Disc_No { get; set; }
        public bool Active { get; set; }
        public string DayNm { get; set; }
        public bool Food_Disc { get; set; }
        public int Food_No { get; set; }
        public short Disc_Type { get; set; }
        public double Disc_Amt { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<System.DateTime> From_Time { get; set; }
        public Nullable<System.DateTime> To_Time { get; set; }
        public int Food_Grp { get; set; }
        public short Branch_No { get; set; }
        public int PromoType { get; set; }
        public double MainQty { get; set; }
        public int PromoFood_No { get; set; }
        public double PromoQty { get; set; }
        public int Disc_Ordr { get; set; }
    
        public virtual Discount_MST Discount_MST { get; set; }
        public virtual Food Food { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
