//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount_MST()
        {
            this.Discount_DTL = new HashSet<Discount_DTL>();
        }
    
        public int Disc_No { get; set; }
        public string Disc_Desc { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<System.DateTime> FTime { get; set; }
        public Nullable<System.DateTime> TTime { get; set; }
        public string DiscDays { get; set; }
        public Nullable<short> DiscType { get; set; }
        public Nullable<double> DiscAmt { get; set; }
        public int PromoType { get; set; }
        public Nullable<double> MainQty { get; set; }
        public int PromoFood_No { get; set; }
        public Nullable<double> PromoQty { get; set; }
        public short Branch_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Discount_DTL> Discount_DTL { get; set; }
        [JsonIgnore]
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
