//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers_Work_Days
    {
        public short Day_No { get; set; }
        public short Branch_No { get; set; }
        public int Dr_No { get; set; }
        public Nullable<System.DateTime> P1_FTime { get; set; }
        public Nullable<System.DateTime> P1_TTime { get; set; }
        public Nullable<System.DateTime> P2_FTime { get; set; }
        public Nullable<System.DateTime> P2_TTime { get; set; }
        public bool Stopped { get; set; }
        public bool Active { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
