//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverGp
    {
        public int Op_ID { get; set; }
        public Nullable<int> Dr_No { get; set; }
        public Nullable<System.DateTime> Gps_Date { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public Nullable<short> Branch_No { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
