//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Foods
    {
        public int Emp_No { get; set; }
        public int Food_No { get; set; }
        public Nullable<short> Group_No { get; set; }
        public Nullable<double> Qty { get; set; }
        public bool Only1item { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Food Food { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
