//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employees_Foods = new HashSet<Employees_Foods>();
            this.Restaurant_H = new HashSet<Restaurant_H>();
        }
    
        public int Emp_No { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<short> Group_No { get; set; }
        public string Account_No { get; set; }
        public short Branch_No { get; set; }
        public Nullable<int> Finger_No { get; set; }
        public Nullable<int> Meal_Price { get; set; }
        public short Meals_Count { get; set; }
        public Nullable<int> Acc_Emp_No { get; set; }
        public bool MonthlyBalance { get; set; }
    
        public virtual Employee_Groups Employee_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_Foods> Employees_Foods { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_H> Restaurant_H { get; set; }
    }
}
