//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalutionMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvalutionMST()
        {
            this.EvalutionDTLs = new HashSet<EvalutionDTL>();
        }
    
        public int EvlNo { get; set; }
        public int ModelID { get; set; }
        public Nullable<System.DateTime> EvlDate { get; set; }
        public Nullable<System.DateTime> EvlTime { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerSuggestion { get; set; }
        public Nullable<int> POS_No { get; set; }
        public Nullable<short> Branch_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvalutionDTL> EvalutionDTLs { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
