//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalutionModelDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvalutionModelDetail()
        {
            this.EvalutionModelEstimates = new HashSet<EvalutionModelEstimate>();
        }
    
        public short ModelID { get; set; }
        public short ElemID { get; set; }
        public Nullable<short> EstmDegree { get; set; }
    
        public virtual EvalutionElement EvalutionElement { get; set; }
        public virtual EvalutionModel EvalutionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvalutionModelEstimate> EvalutionModelEstimates { get; set; }
    }
}
