//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalutionDTL
    {
        public int EvlNo { get; set; }
        public short ModelID { get; set; }
        public short ElmID { get; set; }
        public short EstmID { get; set; }
        public int ElmResult { get; set; }
        public int ElmRatio { get; set; }
    
        public virtual EvalutionMST EvalutionMST { get; set; }
    }
}
