//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalutionModelEstimate
    {
        public short ModelID { get; set; }
        public short ElemID { get; set; }
        public short EstmID { get; set; }
        public Nullable<short> EstmDegree { get; set; }
    
        public virtual EvalutionEstimate EvalutionEstimate { get; set; }
        public virtual EvalutionModelDetail EvalutionModelDetail { get; set; }
    }
}
