//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foods_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foods_Groups()
        {
            this.Foods = new HashSet<Food>();
            this.Groups_Items = new HashSet<Groups_Items>();
            this.POS_Printers = new HashSet<POS_Printers>();
        }
    
        public short Group_No { get; set; }
        public string Group_A_Name { get; set; }
        public string Group_E_Name { get; set; }
        public string Group_T_Name { get; set; }
        public Nullable<short> FoodGroup_Type { get; set; }
        public byte[] Group_Pic { get; set; }
        public short Branch_No { get; set; }
        public string Account_No { get; set; }
        public string RT_Acc { get; set; }
        public string Cost_Center { get; set; }
        public Nullable<short> W_Code { get; set; }
        public string Chef_Printer { get; set; }
        public string Chef_Report { get; set; }
        public bool Force_Chef_Printer { get; set; }
        public Nullable<byte> Print_Count { get; set; }
        public string ComputerName { get; set; }
        public Nullable<int> Group_Color { get; set; }
        public Nullable<int> Group_Order { get; set; }
        public bool W_Link { get; set; }
        public bool M_ReQ { get; set; }
        public Nullable<int> Chef_No { get; set; }
        public bool Stop_Print { get; set; }
        public bool Link_W_Item { get; set; }
        public int Main_W_Item { get; set; }
    
        public virtual Chef Chef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
        public virtual Foods_Types Foods_Types { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups_Items> Groups_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS_Printers> POS_Printers { get; set; }
    }
}
