//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodsReport_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodsReport_H()
        {
            this.FoodsReport_D = new HashSet<FoodsReport_D>();
        }
    
        public short Branch_No { get; set; }
        public int Group_No { get; set; }
        public string Group_Name_A { get; set; }
        public string Group_Name_E { get; set; }
        public bool UnUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodsReport_D> FoodsReport_D { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
