//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foods_Units
    {
        public int Unit_No { get; set; }
        public int Food_No { get; set; }
        public Nullable<int> Unit_Size { get; set; }
        public bool Main_Unit { get; set; }
        public decimal Unit_Price { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
