//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foods_Attach
    {
        public int Food_No { get; set; }
        public int Attach_Food_No { get; set; }
        public string Attach_LNm { get; set; }
        public string Attach_FNm { get; set; }
        public Nullable<int> Attach_Price { get; set; }
        public short Branch_No { get; set; }
        public string Attach_PrinterNm { get; set; }
        public short RCRD_NO { get; set; }
    
        [JsonIgnore]
        public virtual Food Food { get; set; }
        [JsonIgnore]
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
