//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAS_OUT_REQUEST_DTL
    {
        public Nullable<int> Rec_ID { get; set; }
        public Nullable<short> OUT_REQ_TYPE { get; set; }
        public Nullable<long> REQ_NO { get; set; }
        public string REQ_SER { get; set; }
        public int Food_No { get; set; }
        public Nullable<double> I_QTY { get; set; }
        public Nullable<double> P_QTY { get; set; }
        public Nullable<short> W_CODE { get; set; }
        public string ITEM_DESC { get; set; }
        public Nullable<long> DocSer { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual IAS_OUT_REQUEST_MST IAS_OUT_REQUEST_MST { get; set; }
        public virtual REQUEST_TYPES REQUEST_TYPES { get; set; }
        public virtual WAREHOUSE_DETAILS WAREHOUSE_DETAILS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
