//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAS_OUT_REQUEST_MST
    {
        public int Rec_ID { get; set; }
        public Nullable<short> OUT_REQ_TYPE { get; set; }
        public Nullable<long> REQ_NO { get; set; }
        public string REQ_SER { get; set; }
        public Nullable<System.DateTime> OUT_REQ_DATE { get; set; }
        public Nullable<short> W_CODE { get; set; }
        public Nullable<short> F_W_CODE { get; set; }
        public string CC_CODE { get; set; }
        public string REF_NO { get; set; }
        public string REQ_SIDE { get; set; }
        public string DOC_DESC { get; set; }
        public bool PROCESSED { get; set; }
        public bool B_Sync { get; set; }
        public bool P_Onyx { get; set; }
        public bool Rec_Read { get; set; }
        public Nullable<short> User_ID { get; set; }
        public short Branch_No { get; set; }
        public Nullable<int> DlvryWCode { get; set; }
        public Nullable<int> DlvryReQType { get; set; }
        public long DocSer { get; set; }
        public Nullable<int> POS_No { get; set; }
    
        public virtual COST_CENTERS COST_CENTERS { get; set; }
        public virtual REQUEST_TYPES REQUEST_TYPES { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual WAREHOUSE_DETAILS WAREHOUSE_DETAILS { get; set; }
    }
}
