//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAS_NO_ITM_FOUND
    {
        public int Food_No { get; set; }
        public string Food_Name { get; set; }
        public string I_CODE { get; set; }
        public string ITM_UNT { get; set; }
        public Nullable<float> P_SIZE { get; set; }
        public Nullable<short> Branch_No { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
