//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InComing_DTL
    {
        public long Doc_SeQ { get; set; }
        public Nullable<int> Doc_No { get; set; }
        public int Food_No { get; set; }
        public Nullable<double> I_QTY { get; set; }
        public Nullable<short> W_CODE { get; set; }
        public Nullable<double> Food_Price { get; set; }
        public string Food_Desc { get; set; }
        public short Incom_Type { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<int> RCRD_No { get; set; }
        public short Branch_No { get; set; }
        public bool B_Sync { get; set; }
        public Nullable<long> DocSer { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Incoming_Types Incoming_Types { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual InComing_Mst InComing_Mst { get; set; }
    }
}
