//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Move
    {
        public long SN_No { get; set; }
        public long Doc_No { get; set; }
        public short Doc_Type { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public int Food_No { get; set; }
        public double F_Qty { get; set; }
        public double S_Qty { get; set; }
        public Nullable<double> P_Size { get; set; }
        public Nullable<int> Main_Food_No { get; set; }
        public double Main_Qty { get; set; }
        public double F_Price { get; set; }
        public string F_Unit { get; set; }
        public string BarCode_No { get; set; }
        public Nullable<short> W_Code { get; set; }
        public short InOut { get; set; }
        public int Attach_Food_No { get; set; }
        public int RCRD_NO { get; set; }
        public short User_ID { get; set; }
        public int POS_No { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public bool B_Sync { get; set; }
        public bool U_Sync { get; set; }
        public Nullable<short> Branch_No { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
