//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAchv
    {
        public long ASerial { get; set; }
        public Nullable<double> Max_Achv { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> Handle_Date { get; set; }
        public Nullable<System.DateTime> Handle_Time { get; set; }
        public Nullable<double> Act_Achv { get; set; }
        public Nullable<int> Service_No { get; set; }
        public short Branch_No { get; set; }
        public bool Order_Done { get; set; }
        public int POS_No { get; set; }
    
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
