//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalTable
    {
        public string A_Code { get; set; }
        public Nullable<int> Cash_Service { get; set; }
        public string Cost_Center { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<decimal> P_Amount { get; set; }
        public Nullable<decimal> P_AmountF { get; set; }
        public Nullable<System.DateTime> P_Date { get; set; }
        public string P_Desc { get; set; }
        public Nullable<System.DateTime> P_Time { get; set; }
        public bool P_Type { get; set; }
        public bool Posted { get; set; }
        public int Res_No { get; set; }
        public long Room_No { get; set; }
        public int Service_No { get; set; }
        public bool Verified { get; set; }
        public bool Totals { get; set; }
        public int Serial_No { get; set; }
        public Nullable<int> Ref_Serial { get; set; }
        public Nullable<long> Doc_No { get; set; }
        public Nullable<double> BSerial_No { get; set; }
        public int Doc_Type { get; set; }
        public int Bill_Pay_Type { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<long> Cust_No { get; set; }
        public int Emp_No { get; set; }
        public string C_Code { get; set; }
        public short CV_Type { get; set; }
        public int Post_No { get; set; }
        public short AC_DTL_TYP { get; set; }
        public int Cash_No { get; set; }
        public int Bank_No { get; set; }
    }
}
