//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNTNC_REQ
    {
        public int MNT_No { get; set; }
        public Nullable<System.DateTime> MNT_Date { get; set; }
        public Nullable<System.DateTime> MNT_Time { get; set; }
        public string MNT_Desc { get; set; }
        public Nullable<short> User_ID { get; set; }
        public short Status_No { get; set; }
        public short Branch_No { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual User User { get; set; }
    }
}
