//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_TYPES
    {
        public int OUT_TYPE_NO { get; set; }
        public string OUT_NAME_L { get; set; }
        public string OUT_NAME_F { get; set; }
        public string OUT_ACC { get; set; }
        public string PJ_NO { get; set; }
        public string CC_CODE { get; set; }
        public string ACTV_NO { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
