//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Meal_DTL_EXP
    {
        public int Trans_ID { get; set; }
        public int Food_No { get; set; }
        public short Sec_No { get; set; }
        public int Expnd_No { get; set; }
        public double EXP_Per { get; set; }
        public double EXP_Val { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
