//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penality
    {
        public int Penality_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> P_Date { get; set; }
        public string P_Desc { get; set; }
        public bool Posted { get; set; }
        public Nullable<short> User_ID { get; set; }
        public short Branch_No { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
