//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Printers
    {
        public int POS_No { get; set; }
        public short Group_No { get; set; }
        public string PosPrinterName { get; set; }
        public short CopyCount { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Foods_Groups Foods_Groups { get; set; }
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
