//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RES_BILL_COMPND_DTL
    {
        public long Bill_No { get; set; }
        public string BILL_SER { get; set; }
        public string I_Code { get; set; }
        public string ITM_UNT { get; set; }
        public Nullable<double> P_SIZE { get; set; }
        public Nullable<double> I_QTY { get; set; }
        public Nullable<double> P_QTY { get; set; }
        public string DI_Code { get; set; }
        public string DITM_UNT { get; set; }
        public Nullable<double> DP_SIZE { get; set; }
        public Nullable<double> DI_QTY { get; set; }
        public Nullable<double> DP_QTY { get; set; }
        public Nullable<short> W_Code { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public int Batch_No { get; set; }
        public Nullable<long> RCRD_NO { get; set; }
    }
}
