//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RES_STK_DTL
    {
        public int STK_TYPE { get; set; }
        public int DOC_NO { get; set; }
        public Nullable<long> Doc_Ser { get; set; }
        public string I_Code { get; set; }
        public string ITM_UNT { get; set; }
        public Nullable<double> P_SIZE { get; set; }
        public Nullable<double> I_QTY { get; set; }
        public Nullable<double> P_QTY { get; set; }
        public short w_code { get; set; }
        public string CC_Code { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public Nullable<int> ITEM_DESC { get; set; }
        public Nullable<long> RCRD_NO { get; set; }
        public Nullable<long> Stk_ID { get; set; }
    }
}
