//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Res_No { get; set; }
        public Nullable<short> Table_No { get; set; }
        public string Person_Name { get; set; }
        public string Tel_No { get; set; }
        public Nullable<System.DateTime> Res_Date { get; set; }
        public Nullable<System.DateTime> From_Time { get; set; }
        public Nullable<System.DateTime> To_Time { get; set; }
        public bool Alert { get; set; }
        public Nullable<System.DateTime> AlertTime { get; set; }
        public Nullable<short> User_ID { get; set; }
        public string Note { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
        public bool Closed { get; set; }
        public int POS_No { get; set; }
        public long ASerial { get; set; }
        public int Sync_No { get; set; }
        public short Branch_No { get; set; }
        public Nullable<short> Section_No { get; set; }
    
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
