//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserved_Foods_Canceled
    {
        public int Res_No { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<System.DateTime> C_Time { get; set; }
        public Nullable<long> Customer_No { get; set; }
        public string C_Desc { get; set; }
        public int Voucher_No { get; set; }
        public decimal Return_Amount { get; set; }
        public int Ins_No { get; set; }
        public Nullable<short> User_ID { get; set; }
        public short Branch_No { get; set; }
        public bool Acc_Posted { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
