//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_InvoTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant_InvoTypes()
        {
            this.Deleted_H = new HashSet<Deleted_H>();
            this.HstrRest_H = new HashSet<HstrRest_H>();
            this.Restaurant_H = new HashSet<Restaurant_H>();
        }
    
        public short Type_No { get; set; }
        public string Type_Name { get; set; }
        public string Type_E_Name { get; set; }
        public Nullable<float> Tax { get; set; }
        public Nullable<byte> Service_Charges { get; set; }
        public Nullable<byte> Discount { get; set; }
        public short Branch_No { get; set; }
        public short Target_Type { get; set; }
        public bool Stop_Type { get; set; }
        public string Chef_Printer { get; set; }
        public bool Force_Chef_Printer { get; set; }
        public Nullable<short> Bill_Copy_No { get; set; }
        public Nullable<short> Print_Copy_No { get; set; }
        public bool CopyChefOrders { get; set; }
        public string CopyChefOrdersPrinter { get; set; }
        public Nullable<long> Feed_Cust_No { get; set; }
        public int Use_Android { get; set; }
        public int StopPrintCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deleted_H> Deleted_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HstrRest_H> HstrRest_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_H> Restaurant_H { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
