//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant_Info()
        {
            this.AccSys_Accounts = new HashSet<AccSys_Accounts>();
            this.Areas = new HashSet<Area>();
            this.Areas_Drivers = new HashSet<Areas_Drivers>();
            this.Benches = new HashSet<Bench>();
            this.Benches_Sections = new HashSet<Benches_Sections>();
            this.Bills_Components = new HashSet<Bills_Components>();
            this.Bills_Notes_Mst = new HashSet<Bills_Notes_Mst>();
            this.Black_List = new HashSet<Black_List>();
            this.Cells = new HashSet<Cell>();
            this.Cells_Groups = new HashSet<Cells_Groups>();
            this.Chefs = new HashSet<Chef>();
            this.COST_CENTERS = new HashSet<COST_CENTERS>();
            this.CreditCards = new HashSet<CreditCard>();
            this.Currency_Categories = new HashSet<Currency_Categories>();
            this.Customer_Promo_MST = new HashSet<Customer_Promo_MST>();
            this.Customers_Accounts = new HashSet<Customers_Accounts>();
            this.Customers_Payment = new HashSet<Customers_Payment>();
            this.Damage_DTL = new HashSet<Damage_DTL>();
            this.Damage_MST = new HashSet<Damage_MST>();
            this.Damage_Types = new HashSet<Damage_Types>();
            this.Deleted_D = new HashSet<Deleted_D>();
            this.Deleted_H = new HashSet<Deleted_H>();
            this.DeleteRests = new HashSet<DeleteRest>();
            this.Discount_MST = new HashSet<Discount_MST>();
            this.Dlvr_Dtl = new HashSet<Dlvr_Dtl>();
            this.Drivers = new HashSet<Driver>();
            this.Drivers_Work_Days = new HashSet<Drivers_Work_Days>();
            this.Employee_Groups = new HashSet<Employee_Groups>();
            this.Employees = new HashSet<Employee>();
            this.Employees_Foods = new HashSet<Employees_Foods>();
            this.EvalutionMSTs = new HashSet<EvalutionMST>();
            this.FingerDevices = new HashSet<FingerDevice>();
            this.Foods = new HashSet<Food>();
            this.Foods_Altrantv = new HashSet<Foods_Altrantv>();
            this.Foods_Attach = new HashSet<Foods_Attach>();
            this.Foods_Combo = new HashSet<Foods_Combo>();
            this.Foods_Components = new HashSet<Foods_Components>();
            this.Foods_Components_End = new HashSet<Foods_Components_End>();
            this.Foods_Groups = new HashSet<Foods_Groups>();
            this.Foods_Prices = new HashSet<Foods_Prices>();
            this.Foods_Types = new HashSet<Foods_Types>();
            this.Foods_Units = new HashSet<Foods_Units>();
            this.FoodsReport_D = new HashSet<FoodsReport_D>();
            this.FoodsReport_H = new HashSet<FoodsReport_H>();
            this.Groups_Items = new HashSet<Groups_Items>();
            this.HstrRest_D = new HashSet<HstrRest_D>();
            this.HstrRest_D_Combo = new HashSet<HstrRest_D_Combo>();
            this.HstrRest_D_DTL = new HashSet<HstrRest_D_DTL>();
            this.HstrRest_H = new HashSet<HstrRest_H>();
            this.IAS_OUT_REQUEST_MST = new HashSet<IAS_OUT_REQUEST_MST>();
            this.InComing_DTL = new HashSet<InComing_DTL>();
            this.InComing_Mst = new HashSet<InComing_Mst>();
            this.Incoming_Types = new HashSet<Incoming_Types>();
            this.Insurance_Bills_DTL = new HashSet<Insurance_Bills_DTL>();
            this.Insurance_Materials = new HashSet<Insurance_Materials>();
            this.Insurances = new HashSet<Insurance>();
            this.Insurances_Closed = new HashSet<Insurances_Closed>();
            this.Insurances_Deleted = new HashSet<Insurances_Deleted>();
            this.Inventory_MST = new HashSet<Inventory_MST>();
            this.Item_Move = new HashSet<Item_Move>();
            this.ItemAchvs = new HashSet<ItemAchv>();
            this.Items_Notes_Dtl = new HashSet<Items_Notes_Dtl>();
            this.Items_Notes_Mst = new HashSet<Items_Notes_Mst>();
            this.List_States = new HashSet<List_States>();
            this.MNTNC_REQ = new HashSet<MNTNC_REQ>();
            this.MyPoints_DTL = new HashSet<MyPoints_DTL>();
            this.OpenBuffets = new HashSet<OpenBuffet>();
            this.Options_Privileges = new HashSet<Options_Privileges>();
            this.OrderMethods = new HashSet<OrderMethod>();
            this.OUT_TYPES = new HashSet<OUT_TYPES>();
            this.Penalities = new HashSet<Penality>();
            this.POS = new HashSet<POS>();
            this.POS_Printers = new HashSet<POS_Printers>();
            this.Printers = new HashSet<Printer>();
            this.Privileges = new HashSet<Privilege>();
            this.Privileges_SBF = new HashSet<Privileges_SBF>();
            this.ProductionRequestComponents = new HashSet<ProductionRequestComponent>();
            this.ProductionRequestDtls = new HashSet<ProductionRequestDtl>();
            this.ProductionRequestMsts = new HashSet<ProductionRequestMst>();
            this.REQUEST_TYPES = new HashSet<REQUEST_TYPES>();
            this.RES_WHTRNS_DTL = new HashSet<RES_WHTRNS_DTL>();
            this.RES_WHTRNS_MST = new HashSet<RES_WHTRNS_MST>();
            this.Reservations = new HashSet<Reservation>();
            this.Reserved_Foods = new HashSet<Reserved_Foods>();
            this.Reserved_Foods_Canceled = new HashSet<Reserved_Foods_Canceled>();
            this.Reserved_Foods_Items = new HashSet<Reserved_Foods_Items>();
            this.Rest_Taxes = new HashSet<Rest_Taxes>();
            this.Restaurant_D = new HashSet<Restaurant_D>();
            this.Restaurant_H = new HashSet<Restaurant_H>();
            this.ConfirmConsume_DTL = new HashSet<ConfirmConsume_DTL>();
            this.ConfirmConsume_MST = new HashSet<ConfirmConsume_MST>();
            this.Customer_Promo_DTL = new HashSet<Customer_Promo_DTL>();
            this.Damage_Components = new HashSet<Damage_Components>();
            this.Discount_DTL = new HashSet<Discount_DTL>();
            this.DriverGps = new HashSet<DriverGp>();
            this.IAS_NO_ITM_FOUND = new HashSet<IAS_NO_ITM_FOUND>();
            this.IAS_OUT_REQUEST_DTL = new HashSet<IAS_OUT_REQUEST_DTL>();
            this.Inventory_DTL = new HashSet<Inventory_DTL>();
            this.PrinterDetails = new HashSet<PrinterDetail>();
            this.Restaurant_Bill_No = new HashSet<Restaurant_Bill_No>();
            this.Restaurant_InvoTypes = new HashSet<Restaurant_InvoTypes>();
            this.Restaurant_Menus_Food = new HashSet<Restaurant_Menus_Food>();
            this.Restaurant_Menus = new HashSet<Restaurant_Menus>();
            this.Restaurant_Orders = new HashSet<Restaurant_Orders>();
            this.Restaurant_Periods = new HashSet<Restaurant_Periods>();
            this.Restaurant_Shortcuts = new HashSet<Restaurant_Shortcuts>();
            this.RSRVD_Payments = new HashSet<RSRVD_Payments>();
            this.RSRVD_RefundPayment = new HashSet<RSRVD_RefundPayment>();
            this.RT_Bill_DTL_DTL = new HashSet<RT_Bill_DTL_DTL>();
            this.RT_Bill_DTL = new HashSet<RT_Bill_DTL>();
            this.RT_Bill_MST = new HashSet<RT_Bill_MST>();
            this.RT_Ins_DTL = new HashSet<RT_Ins_DTL>();
            this.RT_Ins_MST = new HashSet<RT_Ins_MST>();
            this.SchduleOptions = new HashSet<SchduleOption>();
            this.SMS_DTL = new HashSet<SMS_DTL>();
            this.SMS_Suplliers = new HashSet<SMS_Suplliers>();
            this.Spends = new HashSet<Spend>();
            this.Spends_Types = new HashSet<Spends_Types>();
            this.Split_Bills = new HashSet<Split_Bills>();
            this.Stock_Adjst_DTL = new HashSet<Stock_Adjst_DTL>();
            this.Stock_Adjst_MST = new HashSet<Stock_Adjst_MST>();
            this.Stock_QtyAv = new HashSet<Stock_QtyAv>();
            this.Streets = new HashSet<Street>();
            this.Sub_Items = new HashSet<Sub_Items>();
            this.SyncDatas = new HashSet<SyncData>();
            this.System_Options = new HashSet<System_Options>();
            this.Tables_Status = new HashSet<Tables_Status>();
            this.Transfer_Orders = new HashSet<Transfer_Orders>();
            this.TRANSFER_TYPES = new HashSet<TRANSFER_TYPES>();
            this.Units = new HashSet<Unit>();
            this.User_Income = new HashSet<User_Income>();
            this.Users_Acc_Link = new HashSet<Users_Acc_Link>();
            this.Users_Actions = new HashSet<Users_Actions>();
            this.Users_Current_Login = new HashSet<Users_Current_Login>();
            this.Users_History = new HashSet<Users_History>();
            this.Users_Login = new HashSet<Users_Login>();
            this.Users_Options = new HashSet<Users_Options>();
            this.Users_Periods = new HashSet<Users_Periods>();
            this.Waiters_Privileges = new HashSet<Waiters_Privileges>();
            this.Waiters = new HashSet<Waiter>();
            this.WAREHOUSE_DETAILS = new HashSet<WAREHOUSE_DETAILS>();
            this.WareHouses = new HashSet<WareHouse>();
        }
    
        public short Branch_No { get; set; }
        public string A_Name { get; set; }
        public string E_Name { get; set; }
        public string A_Header1 { get; set; }
        public string A_Header2 { get; set; }
        public string A_Header3 { get; set; }
        public string E_Header1 { get; set; }
        public string E_Header2 { get; set; }
        public string E_Header3 { get; set; }
        public string Chef_Printer { get; set; }
        public string Invoice_Printer { get; set; }
        public string Invoice_Printer2 { get; set; }
        public string Account_No { get; set; }
        public string Tax_Account { get; set; }
        public string Cost_Center { get; set; }
        public string Rest_Store_Acc { get; set; }
        public string Srv_Account { get; set; }
        public string Discount_Acc { get; set; }
        public string Damaged_Acc { get; set; }
        public string Penality_Acc { get; set; }
        public string Insurance_Acc { get; set; }
        public string Material_Warranty_Acc { get; set; }
        public string ResFoods_Acc { get; set; }
        public string Spends_Acc { get; set; }
        public string CCI_Acc { get; set; }
        public short FA_Branch_No { get; set; }
        public Nullable<short> FA_Year { get; set; }
        public Nullable<int> FA_Warehouse { get; set; }
        public Nullable<short> FA_Out_W_Code { get; set; }
        public Nullable<int> Hotel_Year { get; set; }
        public Nullable<short> Hotel_Branch { get; set; }
        public Nullable<short> Hotel_DataType { get; set; }
        public string Hotel_Server { get; set; }
        public string Hotel_Path { get; set; }
        public bool SaveMultiHotelServices { get; set; }
        public Nullable<short> Restart_Type { get; set; }
        public Nullable<int> Restart_No { get; set; }
        public Nullable<double> WhenBillNo { get; set; }
        public string Service_Acc { get; set; }
        public string Round_Acc { get; set; }
        public Nullable<System.DateTime> First_Hour { get; set; }
        public Nullable<short> FA_Type { get; set; }
        public string FA_Path { get; set; }
        public Nullable<short> Onyx_Active { get; set; }
        public string CurCode { get; set; }
        public bool UseCreditCard { get; set; }
        public bool UseBarCode { get; set; }
        public bool UseUsersCards { get; set; }
        public Nullable<short> LenUserCard { get; set; }
        public bool UseRound { get; set; }
        public Nullable<short> RoundType { get; set; }
        public Nullable<short> RoundNo { get; set; }
        public bool UseProduct { get; set; }
        public string RestStoreAcc { get; set; }
        public Nullable<short> Price_Type { get; set; }
        public byte[] Logo_Pic { get; set; }
        public Nullable<short> Bill_Serial_Type { get; set; }
        public int Account_Posting_Type { get; set; }
        public int Account_Data_Posting_Type { get; set; }
        public bool LinkAccData { get; set; }
        public bool LinkAccWarehouse { get; set; }
        public string ServerIP { get; set; }
        public string B_Color { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public bool ClosedYear { get; set; }
        public string LocalServer { get; set; }
        public short Acc_Price_Level { get; set; }
        public bool AccMergeUniteWName { get; set; }
        public bool AccNOTUpdateItemName { get; set; }
        public string RT_Bills_Acc { get; set; }
        public bool AccProxy { get; set; }
        public string OnyxPJ_No { get; set; }
        public string OnyxACTV_No { get; set; }
        public short CostCenterBy { get; set; }
        public string TaxNumber { get; set; }
        public bool ItemPriceIncludeTax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccSys_Accounts> AccSys_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Areas_Drivers> Areas_Drivers { get; set; }
        public virtual BarCode_Setup BarCode_Setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bench> Benches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benches_Sections> Benches_Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills_Components> Bills_Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills_Notes_Mst> Bills_Notes_Mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Black_List> Black_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cell> Cells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cells_Groups> Cells_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chef> Chefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COST_CENTERS> COST_CENTERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency_Categories> Currency_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Promo_MST> Customer_Promo_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Accounts> Customers_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Payment> Customers_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_DTL> Damage_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_MST> Damage_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_Types> Damage_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deleted_D> Deleted_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deleted_H> Deleted_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeleteRest> DeleteRests { get; set; }
        public virtual Delivery_Options Delivery_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount_MST> Discount_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dlvr_Dtl> Dlvr_Dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivers_Work_Days> Drivers_Work_Days { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Groups> Employee_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_Foods> Employees_Foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvalutionMST> EvalutionMSTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FingerDevice> FingerDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Altrantv> Foods_Altrantv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Attach> Foods_Attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Combo> Foods_Combo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Components> Foods_Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Components_End> Foods_Components_End { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Groups> Foods_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Prices> Foods_Prices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Types> Foods_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods_Units> Foods_Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodsReport_D> FoodsReport_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodsReport_H> FoodsReport_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups_Items> Groups_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HstrRest_D> HstrRest_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HstrRest_D_Combo> HstrRest_D_Combo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HstrRest_D_DTL> HstrRest_D_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HstrRest_H> HstrRest_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAS_OUT_REQUEST_MST> IAS_OUT_REQUEST_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InComing_DTL> InComing_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InComing_Mst> InComing_Mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incoming_Types> Incoming_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance_Bills_DTL> Insurance_Bills_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance_Materials> Insurance_Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance> Insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurances_Closed> Insurances_Closed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurances_Deleted> Insurances_Deleted { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_MST> Inventory_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Move> Item_Move { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAchv> ItemAchvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_Notes_Dtl> Items_Notes_Dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_Notes_Mst> Items_Notes_Mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_States> List_States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MNTNC_REQ> MNTNC_REQ { get; set; }
        public virtual MyPoint MyPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyPoints_DTL> MyPoints_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenBuffet> OpenBuffets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Options_Privileges> Options_Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMethod> OrderMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUT_TYPES> OUT_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penality> Penalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS> POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS_Printers> POS_Printers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Printer> Printers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Privilege> Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Privileges_SBF> Privileges_SBF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionRequestComponent> ProductionRequestComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionRequestDtl> ProductionRequestDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionRequestMst> ProductionRequestMsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_TYPES> REQUEST_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RES_WHTRNS_DTL> RES_WHTRNS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RES_WHTRNS_MST> RES_WHTRNS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserved_Foods> Reserved_Foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserved_Foods_Canceled> Reserved_Foods_Canceled { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserved_Foods_Items> Reserved_Foods_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rest_Taxes> Rest_Taxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_D> Restaurant_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_H> Restaurant_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmConsume_DTL> ConfirmConsume_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmConsume_MST> ConfirmConsume_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Promo_DTL> Customer_Promo_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_Components> Damage_Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount_DTL> Discount_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverGp> DriverGps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAS_NO_ITM_FOUND> IAS_NO_ITM_FOUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAS_OUT_REQUEST_DTL> IAS_OUT_REQUEST_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_DTL> Inventory_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrinterDetail> PrinterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Bill_No> Restaurant_Bill_No { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_InvoTypes> Restaurant_InvoTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Menus_Food> Restaurant_Menus_Food { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Menus> Restaurant_Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Orders> Restaurant_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Periods> Restaurant_Periods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Shortcuts> Restaurant_Shortcuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRVD_Payments> RSRVD_Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRVD_RefundPayment> RSRVD_RefundPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RT_Bill_DTL_DTL> RT_Bill_DTL_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RT_Bill_DTL> RT_Bill_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RT_Bill_MST> RT_Bill_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RT_Ins_DTL> RT_Ins_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RT_Ins_MST> RT_Ins_MST { get; set; }
        public virtual SaveSetting SaveSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchduleOption> SchduleOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS_DTL> SMS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS_Suplliers> SMS_Suplliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spend> Spends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spends_Types> Spends_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Split_Bills> Split_Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Adjst_DTL> Stock_Adjst_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Adjst_MST> Stock_Adjst_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_QtyAv> Stock_QtyAv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Street> Streets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Items> Sub_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncData> SyncDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Options> System_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tables_Status> Tables_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_Orders> Transfer_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFER_TYPES> TRANSFER_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Income> User_Income { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Acc_Link> Users_Acc_Link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Actions> Users_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Current_Login> Users_Current_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_History> Users_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Login> Users_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Options> Users_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Periods> Users_Periods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waiters_Privileges> Waiters_Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waiter> Waiters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE_DETAILS> WAREHOUSE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareHouse> WareHouses { get; set; }
    }
}
