//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rest_Taxes
    {
        public short Tax_No { get; set; }
        public string Tax_NameA { get; set; }
        public string Tax_NameE { get; set; }
        public Nullable<byte> Tax_Group { get; set; }
        public Nullable<int> Tax_SubGroup { get; set; }
        public bool Tax_Type { get; set; }
        public Nullable<byte> Tax_Per { get; set; }
        public Nullable<double> Tax_Val { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
