//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rest_Targets
    {
        public short Target_No { get; set; }
        public string Target_A_Name { get; set; }
        public string Target_E_Name { get; set; }
        public string Change_Field { get; set; }
        public string Target_SQL { get; set; }
    }
}
