//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSRVD_Payments
    {
        public long P_ID { get; set; }
        public int Pay_No { get; set; }
        public int Res_No { get; set; }
        public Nullable<long> Customer_No { get; set; }
        public decimal Pay_Amount { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public Nullable<System.DateTime> Pay_Time { get; set; }
        public string P_Desc { get; set; }
        public Nullable<short> User_ID { get; set; }
        public Nullable<short> UP_User_ID { get; set; }
        public Nullable<System.DateTime> UP_Date { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public bool P_Posted { get; set; }
        public bool B_Sync { get; set; }
        public bool Acc_Posted { get; set; }
        public bool Printed { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Reserved_Foods Reserved_Foods { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual User User { get; set; }
    }
}
