//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RT_Bill_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RT_Bill_MST()
        {
            this.RT_Bill_DTL = new HashSet<RT_Bill_DTL>();
        }
    
        public long RT_Bill_No { get; set; }
        public long ASerial { get; set; }
        public float Discount { get; set; }
        public Nullable<decimal> Net_Amount { get; set; }
        public decimal Amount_Before_Round { get; set; }
        public Nullable<System.DateTime> RT_Date { get; set; }
        public short Tax { get; set; }
        public Nullable<int> Service_No { get; set; }
        public Nullable<long> Customer_No { get; set; }
        public bool ACC_Posted { get; set; }
        public Nullable<System.DateTime> RT_Time { get; set; }
        public string RT_Desc { get; set; }
        public short Service_Charges { get; set; }
        public Nullable<short> User_ID { get; set; }
        public short Branch_No { get; set; }
        public bool Printed { get; set; }
        public Nullable<double> Discount_Ratio { get; set; }
        public bool QTY_Posted { get; set; }
        public bool Posted { get; set; }
        public Nullable<short> Bill_Pay_Type { get; set; }
        public decimal Extra_Service { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public Nullable<int> Last_Modified_User { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
        public int POS_No { get; set; }
        public int Sync_No { get; set; }
        public int Post_No { get; set; }
        public decimal Dr_Amount { get; set; }
        public Nullable<int> Ins_No { get; set; }
        public bool DiscCard { get; set; }
        public bool PaidByPoints { get; set; }
        public int Bill_Type { get; set; }
        public int Section_No { get; set; }
        public Nullable<short> Table_No { get; set; }
        public int Order_No { get; set; }
        public Nullable<double> Itm_Disc { get; set; }
        public bool Dstrbut_DISC_TAX { get; set; }
        public double ItemsTaxAmt { get; set; }
    
        public virtual Insurance Insurance { get; set; }
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RT_Bill_DTL> RT_Bill_DTL { get; set; }
    }
}
