//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RT_Ins_DTL
    {
        public int RT_Ins_No { get; set; }
        public Nullable<int> Ins_No { get; set; }
        public int M_No { get; set; }
        public string M_Name { get; set; }
        public Nullable<decimal> M_Price { get; set; }
        public Nullable<int> M_Qty { get; set; }
        public Nullable<decimal> M_Amount { get; set; }
        public short RCRD_No { get; set; }
        public short Branch_No { get; set; }
        public Nullable<double> RC_ID { get; set; }
        public int POS_No { get; set; }
        public bool U_Sync { get; set; }
        public bool B_Sync { get; set; }
        public bool FromPastYear { get; set; }
    
        public virtual Insurance_Materials Insurance_Materials { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual POS POS { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual RT_Ins_MST RT_Ins_MST { get; set; }
    }
}
