//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchduleOption
    {
        public int JobType { get; set; }
        public string DBName { get; set; }
        public string ServerName { get; set; }
        public string JobName { get; set; }
        public bool JobActv { get; set; }
        public short ScheduleType { get; set; }
        public Nullable<System.DateTime> RunAt { get; set; }
        public short RunEvery { get; set; }
        public short HourType { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
