//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_DTL
    {
        public short Branch_No { get; set; }
        public short MsgType { get; set; }
        public string MsgTypeNM { get; set; }
        public string MsgText { get; set; }
        public bool MsgActv { get; set; }
        public bool ShowOrderNo { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
