//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Suplliers
    {
        public int Supllier_No { get; set; }
        public string Supllier_Name { get; set; }
        public string U_Name { get; set; }
        public string U_PWD { get; set; }
        public string Sender_Name { get; set; }
        public string URL_Link { get; set; }
        public string URL_Blnc { get; set; }
        public bool SMS_Encrypt { get; set; }
        public string Def_Msg_Text { get; set; }
        public bool ActvSupllier { get; set; }
        public string UserInUrl { get; set; }
        public string PWDInUrl { get; set; }
        public string SenderInUrl { get; set; }
        public string TxtMsgInUrl { get; set; }
        public string PhonNoInUrl { get; set; }
        public short Branch_No { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
