//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Errors
    {
        public long ERR_SN { get; set; }
        public string ERR_NUMBER { get; set; }
        public string ERR_MESSAGE { get; set; }
        public string ERR_SEVERITY { get; set; }
        public string ERR_STATE { get; set; }
        public Nullable<System.DateTime> ERR_DATE { get; set; }
        public short ERR_TYPE { get; set; }
    }
}
