//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Initial
    {
        public bool DemoEnd { get; set; }
        public int Lang { get; set; }
        public Nullable<int> Revision_No { get; set; }
        public Nullable<byte> UpToDate { get; set; }
        public short Country { get; set; }
        public string DBE_Version { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
