//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Options
    {
        public int Option_No { get; set; }
        public int Option_Type { get; set; }
        public string Option_Name_A { get; set; }
        public string Option_Name_E { get; set; }
        public bool Option_Value { get; set; }
        public string Option_Var1 { get; set; }
        public string Option_Var2 { get; set; }
        public short MSG_No { get; set; }
        public short Branch_No { get; set; }
    
        [JsonIgnore]
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
