//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Periods
    {
        public short User_Id { get; set; }
        public short Branch_No { get; set; }
        public int Period_No { get; set; }
        public bool Can_Login { get; set; }
    
        public virtual Restaurant_Info Restaurant_Info { get; set; }
        public virtual Restaurant_Periods Restaurant_Periods { get; set; }
        public virtual User User { get; set; }
    }
}
