//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_History
    {
        public Nullable<short> User_ID { get; set; }
        public int Action_ID { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public Nullable<System.DateTime> Action_Time { get; set; }
        public string Action_Desc { get; set; }
        public Nullable<int> Record_No { get; set; }
        public Nullable<short> Form_No { get; set; }
        public Nullable<short> Action_Type { get; set; }
        public Nullable<decimal> Amount_Before { get; set; }
        public Nullable<decimal> Amount_After { get; set; }
        public Nullable<short> Branch_No { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Form_Details Form_Details { get; set; }
        public virtual Restaurant_Info Restaurant_Info { get; set; }
    }
}
