//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace RestaurantsIntegrationService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customers_Payment = new HashSet<Customers_Payment>();
            this.Damage_MST = new HashSet<Damage_MST>();
            this.DeleteRests = new HashSet<DeleteRest>();
            this.Dlvr_Dtl = new HashSet<Dlvr_Dtl>();
            this.HstrRest_H = new HashSet<HstrRest_H>();
            this.Inventory_MST = new HashSet<Inventory_MST>();
            this.MNTNC_REQ = new HashSet<MNTNC_REQ>();
            this.Options_Privileges = new HashSet<Options_Privileges>();
            this.Privileges = new HashSet<Privilege>();
            this.Privileges_SBF = new HashSet<Privileges_SBF>();
            this.Reserved_Foods = new HashSet<Reserved_Foods>();
            this.Restaurant_Orders = new HashSet<Restaurant_Orders>();
            this.Restaurant_Shortcuts = new HashSet<Restaurant_Shortcuts>();
            this.RSRVD_Payments = new HashSet<RSRVD_Payments>();
            this.RSRVD_RefundPayment = new HashSet<RSRVD_RefundPayment>();
            this.Spends = new HashSet<Spend>();
            this.Tables_Status = new HashSet<Tables_Status>();
            this.User_Income = new HashSet<User_Income>();
            this.ConfirmConsume_DTL = new HashSet<ConfirmConsume_DTL>();
            this.ConfirmConsume_MST = new HashSet<ConfirmConsume_MST>();
            this.Damage_Components = new HashSet<Damage_Components>();
            this.Users_Acc_Link = new HashSet<Users_Acc_Link>();
            this.Users_Login = new HashSet<Users_Login>();
            this.Users_Options = new HashSet<Users_Options>();
            this.Users_Periods = new HashSet<Users_Periods>();
            this.Damage_DTL = new HashSet<Damage_DTL>();
        }
    
        public short User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Account_No { get; set; }
        public string User_Acc_No { get; set; }
        public short Language { get; set; }
        public int User_Type { get; set; }
        public Nullable<byte> Max_Change { get; set; }
        public Nullable<byte> Min_Change { get; set; }
        public short Group_No { get; set; }
        public bool CanChangePassword { get; set; }
        public bool PasswordChangesOnce { get; set; }
        public bool Stopped { get; set; }
        public Nullable<byte> Icons_Size { get; set; }
        public bool Lang_Change { get; set; }
        public Nullable<short> Type_No { get; set; }
        public bool CanLog_AnyTime { get; set; }
        public bool JustCasherWin { get; set; }
        public short WorkType { get; set; }
        public short Pay_Type { get; set; }
        public string Card_ID { get; set; }
        public int EmpNo { get; set; }
        public Nullable<double> CMSN_Per { get; set; }
        public bool CloseYear { get; set; }
        public bool OpenYear { get; set; }
        public Nullable<int> POS_No { get; set; }
        public Nullable<int> Dr_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Customers_Payment> Customers_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Damage_MST> Damage_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DeleteRest> DeleteRests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Dlvr_Dtl> Dlvr_Dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<HstrRest_H> HstrRest_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Inventory_MST> Inventory_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<MNTNC_REQ> MNTNC_REQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Options_Privileges> Options_Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Privilege> Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Privileges_SBF> Privileges_SBF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Reserved_Foods> Reserved_Foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Restaurant_Orders> Restaurant_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Restaurant_Shortcuts> Restaurant_Shortcuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<RSRVD_Payments> RSRVD_Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<RSRVD_RefundPayment> RSRVD_RefundPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Spend> Spends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Tables_Status> Tables_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<User_Income> User_Income { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ConfirmConsume_DTL> ConfirmConsume_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ConfirmConsume_MST> ConfirmConsume_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Damage_Components> Damage_Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Users_Acc_Link> Users_Acc_Link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Users_Login> Users_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Users_Options> Users_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Users_Periods> Users_Periods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Damage_DTL> Damage_DTL { get; set; }
    }
}
